### ISSUE TITLE
Run time error when initializing Rust logger

### ISSUE THREAD

**Issue by DevHalimMahmoud** [Kofituo/RustApplication#1]
I'm getting this error when i try to run the application

No implementation found for void com.example.rustapplication.lib.RustLog.initialiseLogging() (tried Java_com_example_rustapplication_lib_RustLog_initialiseLogging and Java_com_example_rustapplication_lib_RustLog_initialiseLogging__)

**Comment by Kofituo** [comment]
Hi there, could I see the full error?

**Comment by DevHalimMahmoud** [comment]
> FATAL EXCEPTION: main
                                                                                                    Process: com.example.rustapplication, PID: 5921
                                                                                                    java.lang.UnsatisfiedLinkError: No implementation found for void com.example.rustapplication.lib.RustLog.initialiseLogging() (tried Java_com_example_rustapplication_lib_RustLog_initialiseLogging and Java_com_example_rustapplication_lib_RustLog_initialiseLogging__)
                                                                                                    	at com.example.rustapplication.lib.RustLog.initialiseLogging(Native Method)
                                                                                                    	at com.example.rustapplication.MainActivity.<clinit>(MainActivity.kt:23)
                                                                                                    	at java.lang.Class.newInstance(Native Method)
                                                                                                    	at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
                                                                                                    	at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:45)
                                                                                                    	at android.app.Instrumentation.newActivity(Instrumentation.java:1274)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3668)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3938)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2291)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:210)
                                                                                                    	at android.os.Looper.loop(Looper.java:299)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8319)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038)

**Comment by Kofituo** [comment]
Hi there, have you modified the source code a bit?
That could be the cause of the issue. Sorry for the delay.

The error means there's no initialisLogging function found. Either that function is missing or the java_glue.rs fine hasn't been created properly.
